[tox]
envlist = py310, py311, py312, py313, flake8
isolated_build = true

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 kernelmethods

[testenv]
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    python -m pytest --basetemp={envtmpdir}

